site_name: Security Notes
docs_dir: Notes
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search
  - roamlinks
  - tags
  - git-revision-date-localized:
      enabled_creation_date: true
  - callouts
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - tables



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://kloccis1.github.io